version: 0.2
phases:
  pre_build:
    commands:
     - echo Restore started on `date`
     - dotnet restore TestApi/TestApi.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output TestApi/TestApi.csproj
artifacts:
  files:
    - TestApi/build_output/**/*